/*
saturn-bot server API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetTaskV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTaskV1Response{}

// GetTaskV1Response struct for GetTaskV1Response
type GetTaskV1Response struct {
	Name string `json:"name"`
	Hash string `json:"hash"`
	Content string `json:"content"`
}

type _GetTaskV1Response GetTaskV1Response

// NewGetTaskV1Response instantiates a new GetTaskV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTaskV1Response(name string, hash string, content string) *GetTaskV1Response {
	this := GetTaskV1Response{}
	this.Name = name
	this.Hash = hash
	this.Content = content
	return &this
}

// NewGetTaskV1ResponseWithDefaults instantiates a new GetTaskV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTaskV1ResponseWithDefaults() *GetTaskV1Response {
	this := GetTaskV1Response{}
	return &this
}

// GetName returns the Name field value
func (o *GetTaskV1Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetTaskV1Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetTaskV1Response) SetName(v string) {
	o.Name = v
}

// GetHash returns the Hash field value
func (o *GetTaskV1Response) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *GetTaskV1Response) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *GetTaskV1Response) SetHash(v string) {
	o.Hash = v
}

// GetContent returns the Content field value
func (o *GetTaskV1Response) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *GetTaskV1Response) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *GetTaskV1Response) SetContent(v string) {
	o.Content = v
}

func (o GetTaskV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTaskV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["hash"] = o.Hash
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *GetTaskV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"hash",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTaskV1Response := _GetTaskV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTaskV1Response)

	if err != nil {
		return err
	}

	*o = GetTaskV1Response(varGetTaskV1Response)

	return err
}

type NullableGetTaskV1Response struct {
	value *GetTaskV1Response
	isSet bool
}

func (v NullableGetTaskV1Response) Get() *GetTaskV1Response {
	return v.value
}

func (v *NullableGetTaskV1Response) Set(val *GetTaskV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTaskV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTaskV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTaskV1Response(val *GetTaskV1Response) *NullableGetTaskV1Response {
	return &NullableGetTaskV1Response{value: val, isSet: true}
}

func (v NullableGetTaskV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTaskV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


