/*
saturn-bot server API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReportWorkV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportWorkV1Response{}

// ReportWorkV1Response struct for ReportWorkV1Response
type ReportWorkV1Response struct {
	// Indicator of the result of the operation.
	Result string `json:"result"`
}

type _ReportWorkV1Response ReportWorkV1Response

// NewReportWorkV1Response instantiates a new ReportWorkV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportWorkV1Response(result string) *ReportWorkV1Response {
	this := ReportWorkV1Response{}
	this.Result = result
	return &this
}

// NewReportWorkV1ResponseWithDefaults instantiates a new ReportWorkV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportWorkV1ResponseWithDefaults() *ReportWorkV1Response {
	this := ReportWorkV1Response{}
	return &this
}

// GetResult returns the Result field value
func (o *ReportWorkV1Response) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ReportWorkV1Response) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *ReportWorkV1Response) SetResult(v string) {
	o.Result = v
}

func (o ReportWorkV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportWorkV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *ReportWorkV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportWorkV1Response := _ReportWorkV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReportWorkV1Response)

	if err != nil {
		return err
	}

	*o = ReportWorkV1Response(varReportWorkV1Response)

	return err
}

type NullableReportWorkV1Response struct {
	value *ReportWorkV1Response
	isSet bool
}

func (v NullableReportWorkV1Response) Get() *ReportWorkV1Response {
	return v.value
}

func (v *NullableReportWorkV1Response) Set(val *ReportWorkV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableReportWorkV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableReportWorkV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportWorkV1Response(val *ReportWorkV1Response) *NullableReportWorkV1Response {
	return &NullableReportWorkV1Response{value: val, isSet: true}
}

func (v NullableReportWorkV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportWorkV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


