// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package api

import (
	"context"
	"net/http"
)



// WorkerAPIRouter defines the required methods for binding the api requests to a responses for the WorkerAPI
// The WorkerAPIRouter implementation should parse necessary information from the http request,
// pass the data to a WorkerAPIServicer to perform the required actions, then write the service results to the http response.
type WorkerAPIRouter interface { 
	GetWorkV1(http.ResponseWriter, *http.Request)
	ReportWorkV1(http.ResponseWriter, *http.Request)
}


// WorkerAPIServicer defines the api actions for the WorkerAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type WorkerAPIServicer interface { 
	GetWorkV1(context.Context) (ImplResponse, error)
	ReportWorkV1(context.Context, ReportWorkV1Request) (ImplResponse, error)
}
