// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package api

import (
	"context"
	"net/http"
	"errors"
)

// WorkerAPIService is a service that implements the logic for the WorkerAPIServicer
// This service should implement the business logic for every endpoint for the WorkerAPI API.
// Include any external packages or services that will be required by this service.
type WorkerAPIService struct {
}

// NewWorkerAPIService creates a default api service
func NewWorkerAPIService() *WorkerAPIService {
	return &WorkerAPIService{}
}

// GetWorkV1 - Get a unit of work.
func (s *WorkerAPIService) GetWorkV1(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetWorkV1 with the required logic for this service method.
	// Add api_worker_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetWorkV1200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetWorkV1200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetWorkV1 method not implemented")
}

// ReportWorkV1 - Report the result of a unit of work
func (s *WorkerAPIService) ReportWorkV1(ctx context.Context, reportWorkV1Request ReportWorkV1Request) (ImplResponse, error) {
	// TODO - update ReportWorkV1 with the required logic for this service method.
	// Add api_worker_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, ReportWorkV1201Response{}) or use other options such as http.Ok ...
	// return Response(201, ReportWorkV1201Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ReportWorkV1 method not implemented")
}
