openapi: 3.1.0
info:
  title: saturn-bot server API
  version: 1.0.0
paths:
  /api/v1/worker/work:
    get:
      operationId: getWorkV1
      summary: Get a unit of work.
      description: Let a worker retrieve the next unit of work.
      tags:
        - worker
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  executionID:
                    description: Internal identifier of the unit of work.
                    type: integer
                  repositories:
                    description: List of repositories for which to apply the task.
                    type: array
                    items:
                      type: string
                  task:
                    description: Name of the task to execute.
                    type: string
                required: ["executionID", "repositories", "task"]
    post:
      operationId: reportWorkV1
      summary: Report the result of a unit of work
      description: Used by workers to report the result of a unit of work.
      tags:
        - worker
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                executionID:
                  description: Internal identifier of the unit of work.
                  type: integer
                repositoryResults:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      result:
                        type: string
              required: ["executionID", "repositoryResults"]
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    description: Indicator of the result of the operation.
                    type: string
                required: ["result"]
