site_name: saturn-bot
nav:
  - index.md
  - installation.md
  - configuration.md
  - ...
theme:
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
hooks:
  - mkdocs-hooks/json_path.py
plugins:
  - awesome-pages
  - search
