// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type GetWorkV1Task struct {

	// Hash of the task. Used to detect if server and worker are out of sync.
	Hash string `json:"hash"`

	// Name of the task to execute.
	Name string `json:"name"`
}

// AssertGetWorkV1TaskRequired checks if the required fields are not zero-ed
func AssertGetWorkV1TaskRequired(obj GetWorkV1Task) error {
	elements := map[string]interface{}{
		"hash": obj.Hash,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGetWorkV1TaskConstraints checks if the values respects the defined constraints
func AssertGetWorkV1TaskConstraints(obj GetWorkV1Task) error {
	return nil
}
