// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ReportWorkV1Response struct {

	// Indicator of the result of the operation.
	Result string `json:"result"`
}

// AssertReportWorkV1ResponseRequired checks if the required fields are not zero-ed
func AssertReportWorkV1ResponseRequired(obj ReportWorkV1Response) error {
	elements := map[string]interface{}{
		"result": obj.Result,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertReportWorkV1ResponseConstraints checks if the values respects the defined constraints
func AssertReportWorkV1ResponseConstraints(obj ReportWorkV1Response) error {
	return nil
}
