// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ReportWorkV1Request struct {

	// General that occurred during the run, if any.
	Error string `json:"error,omitempty"`

	// Internal identifier of the unit of work.
	RunID int32 `json:"runID"`

	// Results of each task.
	TaskResults []ReportWorkV1TaskResult `json:"taskResults,omitempty"`
}

// AssertReportWorkV1RequestRequired checks if the required fields are not zero-ed
func AssertReportWorkV1RequestRequired(obj ReportWorkV1Request) error {
	elements := map[string]interface{}{
		"runID": obj.RunID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.TaskResults {
		if err := AssertReportWorkV1TaskResultRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertReportWorkV1RequestConstraints checks if the values respects the defined constraints
func AssertReportWorkV1RequestConstraints(obj ReportWorkV1Request) error {
	for _, el := range obj.TaskResults {
		if err := AssertReportWorkV1TaskResultConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
