// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi


import (
	"time"
)



type ScheduleRunV1Request struct {

	// Names of the repositories for which to add a run. Leave empty to schedule a run for all repositories the task matches.
	RepositoryNames []string `json:"repositoryNames,omitempty"`

	// Schedule the run after the given time. Uses the current time if empty.
	ScheduleAfter time.Time `json:"scheduleAfter,omitempty"`

	// Name of the task for which to add a run.
	TaskName string `json:"taskName"`

	RunData map[string]string `json:"runData,omitempty"`
}

// AssertScheduleRunV1RequestRequired checks if the required fields are not zero-ed
func AssertScheduleRunV1RequestRequired(obj ScheduleRunV1Request) error {
	elements := map[string]interface{}{
		"taskName": obj.TaskName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertScheduleRunV1RequestConstraints checks if the values respects the defined constraints
func AssertScheduleRunV1RequestConstraints(obj ScheduleRunV1Request) error {
	return nil
}
