// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type GetWorkV1Response struct {

	// Internal identifier of the unit of work.
	RunID int32 `json:"runID"`

	// Repository for which to apply the tasks.
	Repository string `json:"repository,omitempty"`

	// Names of the tasks to execute.
	Tasks []GetWorkV1Task `json:"tasks"`
}

// AssertGetWorkV1ResponseRequired checks if the required fields are not zero-ed
func AssertGetWorkV1ResponseRequired(obj GetWorkV1Response) error {
	elements := map[string]interface{}{
		"runID": obj.RunID,
		"tasks": obj.Tasks,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Tasks {
		if err := AssertGetWorkV1TaskRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetWorkV1ResponseConstraints checks if the values respects the defined constraints
func AssertGetWorkV1ResponseConstraints(obj GetWorkV1Response) error {
	for _, el := range obj.Tasks {
		if err := AssertGetWorkV1TaskConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
