// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type GetWorkV1200Response struct {

	// Internal identifier of the unit of work.
	ExecutionID int32 `json:"executionID"`

	// Repository for which to apply the tasks.
	Repository string `json:"repository"`

	// Names of the tasks to execute.
	Tasks []string `json:"tasks"`
}

// AssertGetWorkV1200ResponseRequired checks if the required fields are not zero-ed
func AssertGetWorkV1200ResponseRequired(obj GetWorkV1200Response) error {
	elements := map[string]interface{}{
		"executionID": obj.ExecutionID,
		"repository": obj.Repository,
		"tasks": obj.Tasks,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGetWorkV1200ResponseConstraints checks if the values respects the defined constraints
func AssertGetWorkV1200ResponseConstraints(obj GetWorkV1200Response) error {
	return nil
}
