// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type GetTaskV1200Response struct {

	Name string `json:"name"`

	Hash string `json:"hash"`

	Content string `json:"content"`
}

// AssertGetTaskV1200ResponseRequired checks if the required fields are not zero-ed
func AssertGetTaskV1200ResponseRequired(obj GetTaskV1200Response) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"hash": obj.Hash,
		"content": obj.Content,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGetTaskV1200ResponseConstraints checks if the values respects the defined constraints
func AssertGetTaskV1200ResponseConstraints(obj GetTaskV1200Response) error {
	return nil
}
