// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ListTasksV1Response struct {

	// Names of registered tasks.
	Tasks []string `json:"tasks"`
}

// AssertListTasksV1ResponseRequired checks if the required fields are not zero-ed
func AssertListTasksV1ResponseRequired(obj ListTasksV1Response) error {
	elements := map[string]interface{}{
		"tasks": obj.Tasks,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertListTasksV1ResponseConstraints checks if the values respects the defined constraints
func AssertListTasksV1ResponseConstraints(obj ListTasksV1Response) error {
	return nil
}
