// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * saturn-bot server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ReportWorkV1Request struct {

	// Internal identifier of the unit of work.
	ExecutionID int32 `json:"executionID"`

	TaskResults []ReportWorkV1RequestTaskResultsInner `json:"taskResults"`
}

// AssertReportWorkV1RequestRequired checks if the required fields are not zero-ed
func AssertReportWorkV1RequestRequired(obj ReportWorkV1Request) error {
	elements := map[string]interface{}{
		"executionID": obj.ExecutionID,
		"taskResults": obj.TaskResults,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.TaskResults {
		if err := AssertReportWorkV1RequestTaskResultsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertReportWorkV1RequestConstraints checks if the values respects the defined constraints
func AssertReportWorkV1RequestConstraints(obj ReportWorkV1Request) error {
	for _, el := range obj.TaskResults {
		if err := AssertReportWorkV1RequestTaskResultsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
