// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../pkg/processor/processor.go
//
// Generated by this command:
//
//	mockgen -package processor -source ../../../pkg/processor/processor.go -destination processor.gen.go
//

// Package processor is a generated GoMock package.
package processor

import (
	reflect "reflect"

	host "github.com/wndhydrnt/saturn-bot/pkg/host"
	processor "github.com/wndhydrnt/saturn-bot/pkg/processor"
	task "github.com/wndhydrnt/saturn-bot/pkg/task"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryTaskProcessor is a mock of RepositoryTaskProcessor interface.
type MockRepositoryTaskProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryTaskProcessorMockRecorder
	isgomock struct{}
}

// MockRepositoryTaskProcessorMockRecorder is the mock recorder for MockRepositoryTaskProcessor.
type MockRepositoryTaskProcessorMockRecorder struct {
	mock *MockRepositoryTaskProcessor
}

// NewMockRepositoryTaskProcessor creates a new mock instance.
func NewMockRepositoryTaskProcessor(ctrl *gomock.Controller) *MockRepositoryTaskProcessor {
	mock := &MockRepositoryTaskProcessor{ctrl: ctrl}
	mock.recorder = &MockRepositoryTaskProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryTaskProcessor) EXPECT() *MockRepositoryTaskProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockRepositoryTaskProcessor) Process(dryRun bool, repo host.Repository, tasks []*task.Task, doFilter bool) []processor.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", dryRun, repo, tasks, doFilter)
	ret0, _ := ret[0].([]processor.ProcessResult)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockRepositoryTaskProcessorMockRecorder) Process(dryRun, repo, tasks, doFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockRepositoryTaskProcessor)(nil).Process), dryRun, repo, tasks, doFilter)
}
