name: Docs Check

on:
  pull_request:
    paths:
      - docs/**
      - mkdocs.yml
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  mkdocs:
    name: Check mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install -r ./docs/requirements.txt
      - name: Build docs
        run: mkdocs build --strict
