name: Docs Check

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  mkdocs:
    name: Check mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install -r ./docs/requirements.txt
      - name: Build docs
        run: mkdocs build --strict
