name: Go Tests

on:
  pull_request:
    paths:
      - "cmd/*"
      - "pkg/*"
      - "go.mod"
      - "*.go"
  push:
    branches:
      - main
    paths:
      - "cmd/*"
      - "pkg/*"
      - "go.mod"
      - "*.go"

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24.x"]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build binary
        run: make build
      - name: Generate code
        run: go generate ./...
      - name: Check diff
        run: git diff --exit-code .
      - name: Run tests
        run: make test_cover
