name: Hadolint

on:
  pull_request:
    paths:
      - Dockerfile
      - full.Dockerfile
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - full.Dockerfile

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: full.Dockerfile
